apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-worker
  namespace: go-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-worker
  template:
    metadata:
      labels:
        app: go-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: go-worker
      containers:
        - name: go-worker
          image: <ECR_REPO>/go-worker:latest
          ports:
            - containerPort: 8080
          env:
            - name: QUEUE_URL
              value: <SQS_URL>
