apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-worker
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/SEU_USUARIO/aws-cloud-native-playground
    path: k8s/workloads/go-worker
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: go-worker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
